### ISSUE TITLE
Hey guys lets use this for a check list of what we need to Do

### ISSUE THREAD

**Issue by Cmoconnor0823** [Cmoconnor0823/Games-For-All#18]
I'm starting this list with what we last had agreed upon in class

pick a ESRB rating
que up a rating gif
update selection to fire base
pick a platform
que up a platform gif
update selection to fire base
pick a genre
que up a genre gif
update selection to fire base
search button click event
replace drop downs with gifs
populate 10 results
dynamically create cards with:
title
picture
description

This was the better written list Ruben typed out Thursday night but It has items I personally don't remember going over contained in it, but that's more on the firebase side so I most likely missed that bit. 

**Left to do projects :
Update query with user selections
Get 10 results from query
Assign values to cards
Dynamically create 10 cards
Style  card display
Replace drop down with equivalent gif once selected

Firebase events:
Record genre, rating, and console. Location? 
Once MVP is complete:
Select multiple consoles, genres, and/or ratings. 
Admin login and firebase data display page. 
Replace card images with gifs of games
Include ESRB icons in drop down menu. 
Add favorite games to list
Eliminate games already owned/completed  and repopulate with a new result.
Sound events with selections and search buttons (edited) **

**Comment by martucazpo** [comment]
Dropdowns are replaced by gifs, see buttons, one dynamic card is made, can be copied and pasted to make more

**Comment by Cmoconnor0823** [comment]
I've got one possible option for hiding the search bar but I'm looking for something cleaner and I'm currently trying to merge Marco's button code so we have it for tomorrow. I'd be cool if I could get everyone's opinions with styling but in the mean time I'm trying to find some documentation to help polish everything up.

**Comment by martucazpo** [comment]
Also (sorry am on my phone), dynamic cards can be made by array, just set Id to index of array so it makes separate cards for each return

**Comment by rubenavaldez** [comment]
I was thinking a for loop, iterate the through results which I believe is already an array when it returns from the query.
