### ISSUE TITLE
New Html

### ISSUE THREAD

**Issue by martucazpo** [Cmoconnor0823/Games-For-All#19]
Hey Caitlin, the new html is to make the card when Ruben's search engine gives out the results they need to populate 10 cards. (Design wise, maybe 9 would be a better number, 3 rows of 3). This is just one card generated by the search engine results, so it takes up all the card-deck space. In practice there would be at least two other cards in the row. I took them from the bootstrap card-table page. The only change to the index page is the div -- but again, with more cards it might need to be three divs, one for each group of three or more cards. Also, I will be at a luutopahko until midnight, but will arrive refreshed and ready to cheerfully answer any questions tomorrow. Have a good evening!

**Comment by Jonbonbroski** [comment]
ourtablebootcamp.gmail.com
password letMeInPlease
