### ISSUE TITLE
need a new tech for MVP

### ISSUE THREAD

**Issue by rubenavaldez** [Cmoconnor0823/Games-For-All#25]
The query is working a populating results. However, I am currently using ajax not axios. Our MVP is no longer using a new tech. I can try to refine the query so it's axios not ajax, but seeing as we such a problem with access parameters, it might be better to intergrate a different tech. so far we mention age validation and location service. if these use new tech they may be more viable

**Comment by Cmoconnor0823** [comment]
I can look into the style css sheet Eric slacked out in class as a back up in the mean time.
